### ISSUE TITLE
Issues with the book section 4.4 UART

### ISSUE THREAD

**Issue by dtung2008** [MarkAYoder/PRUCookbook#10]
First of all thanks for making the book freely available. Two suggestions after trying out section 4.4.

1. Should indicate FTDI cable connect to P9_24 and P9_26 properly (not just indicate in the command). The text seems to suggest connect to the FTDI pin on the board, which will confuse less experienced readers like me.

2. Makefile use /tmp/pru0-gen as temporary folder, it will run into permission issue if not run at root. Suggest just put in local.

**Comment by MarkAYoder** [comment]
This section has been rewritten with a new figure.  Let me know if it makes sense.  If not, repoen the issue.
