### ISSUE TITLE
Typos in Table 4 of PRUCookbook/docs/05blocks/blocks.adoc

### ISSUE THREAD

**Issue by erco77** [MarkAYoder/PRUCookbook#11]
Hello!
While looking at Table 4 in PRUCookbook/docs/05blocks/blocks.adoc, there are some strange pin#s in "Table 4. Mapping bit positions to pin names" in the "Black pin" column: "P9_92" and "P9_91". The P8 and P9 connectors only have 46 pins, so 92 and 91 seem out of range.

**Comment by MarkAYoder** [comment]
Good catch.  That was an old notation.  They are now 41b and 42b. Check it out.

Thanks...
