### ISSUE TITLE
PRU Cookbook for BB AI?

### ISSUE THREAD

**Issue by benfischer1** [MarkAYoder/PRUCookbook#12]
Hi. Are there any plans to update this great resource for the BB AI, with its extra PRU units?

thank

**Comment by MarkAYoder** [comment]
I hope to update for the AI this summer.  Thanks for you interest.

--Mark

**Comment by benfischer1** [comment]
Great!  Thanks for your work on this bit’s very helpful. 

Take care

**Comment by MarkAYoder** [comment]
@benfischer1 I just posted a new version of the PRU Cookbook that includes the AI.  Chapter 8 tries to detail how to move code to the AI.

Check it out and let me know what you think.

**Comment by benfischer1** [comment]
Thanks!

Take care
