### ISSUE TITLE
Section 6 example broken on PocketBeagle

### ISSUE THREAD

**Issue by daschachter** [MarkAYoder/PRUCookbook#14]
**Problem**
The example code for Section 6, [`gpio.pru0.c`](https://github.com/MarkAYoder/PRUCookbook/blob/583e7aed44439b0be92f3034f56d4cad4b716f8c/docs/06io/code/gpio.pru0.c), does not run on the PocketBeagle. This code is first referenced in [Section 3: Running a Program; Configuring Pins](https://markayoder.github.io/PRUCookbook/03details/details.html#_compiling_and_running) in the PRU Cookbook. In this section, the output for `source setup.sh` seems to configure P1_36 for the PocketBeagle while the subsequent execution of `make` seems to be running on a BeagleBone Black.

I believe the code runs correctly on the BeagleBone Black, blinking an LED attached to P9_11 (I do not have the hardware to test this). However, the code does not blink an LED attached to P1_36 on a PocketBeagle. It is possible that a different file is supposed to be used with the PocketBeagle, but I have not found such a file.

Looking at [`gpio.pru0.c`](https://github.com/MarkAYoder/PRUCookbook/blob/583e7aed44439b0be92f3034f56d4cad4b716f8c/docs/06io/code/gpio.pru0.c), the reason the code is not working on the PocketBeagle is that the code is designed to blink an LED connected to GPIO0[30]. On the BeagleBone Black, this is P9_11 (as expected), but on the PocketBeagle this is _not_ P1_36 as I initially assumed. Instead, GPIO0[30] is P2_05 on the PocketBeagle.

A seemingly simple solution would be to change `source setup.sh` to configure P2_05 instead of P1_36 on the PocketBeagle. Unfortunately, P2_05 is not connected to a PRU, so this will not work.

**Potential Solutions**
I can think of 4 potential solutions to this issue, all of which seem relatively simple.

1. I do not think is the case, but if [`gpio.pru0.c`](https://github.com/MarkAYoder/PRUCookbook/blob/583e7aed44439b0be92f3034f56d4cad4b716f8c/docs/06io/code/gpio.pru0.c) is not intended to be run on the PocketBeagle, this issue can be largely ignored. However, it would make sense to replace the output of `source setup.sh` in [Section 3](https://markayoder.github.io/PRUCookbook/03details/details.html#_compiling_and_running) with output from a BeagleBone Black to prevent confusion. Even if this is not the case, doing this might make sense for consistency.
2. A different GPIO pin (i.e. not GPIO30) can be selected for the BeagleBone Black. A GPIO pin should be selected that is connected to the PRU on both the BeagleBone Black and PocketBeagle. This would require minor modifications to [`gpio.pru0.c`](https://github.com/MarkAYoder/PRUCookbook/blob/583e7aed44439b0be92f3034f56d4cad4b716f8c/docs/06io/code/gpio.pru0.c) and [`setup.sh`](https://github.com/MarkAYoder/PRUCookbook/blob/65771e03e4134c69bda30792626daa0dd368ed16/docs/06io/code/setup.sh).
3. A separate PRU file can be written specifically for the PocketBeagle that toggles the output of GPIO3[14] (which is P1_36 on the PocketBeagle). This would require making a copy of [`gpio.pru0.c`](https://github.com/MarkAYoder/PRUCookbook/blob/583e7aed44439b0be92f3034f56d4cad4b716f8c/docs/06io/code/gpio.pru0.c) (e.g. `gpio_pru0_pb.c`) and making slight modifications to it. The user would then have to decide which file to use based on whether he/she is using a BeagleBone Black or a PocketBeagle.
4. The PRU code can be modified to behave differently when running on a BeagleBone Black vs. PocketBeagle. In particular, it would toggle GPIO0[30] when running on a BeagleBone Black and toggle GPIO3[14] when running on a PocketBeagle. This would involve modifying [`gpio.pru0.c`](https://github.com/MarkAYoder/PRUCookbook/blob/583e7aed44439b0be92f3034f56d4cad4b716f8c/docs/06io/code/gpio.pru0.c).

I would be happy to draft a PR addressing this issue, I am just unsure of which of the above (or other) solutions would be best to pursue.

**Comment by MarkAYoder** [comment]
Darren:  Thanks for catching this.  I like the solution of switching to P2_05.  It turns out this example goes through the GPIO not the PRU's R30 register so P2_05 can be used.

The bigger problem is config-pin no longer works with 'in' and 'out'.  I'm running my own config-pin that looks for 'in' and 'out' and handles them correctly.  You can find it in PRUCookbook/docs/common/config-pin.sh.

I'm not sure the cleanest way to fix the config-pin problem.

**Comment by daschachter** [comment]
@MarkAYoder I see what you mean regarding this example using GPIO rather than R30. I agree that switching to P2_05 makes the most sense, and I will work on updating the code.

Regarding `config-pin` not working with 'in' and 'out,' I ran into the same problem. As a temporary fix, I had been using an older version of `config-pin` (found [here](https://github.com/beagleboard/bb.org-overlays/blob/6b45252fe02fee50dee651c5239bfb1132ae7c9d/tools/beaglebone-universal-io/config-pin)). I was discussing this issue with some community members yesterday evening on the IRC chat and it seems like the older `config-pin` shell script I linked to has been replaced by a newer C version. While I have not been able to find the source for this C version, it does not have support for 'in'/'out' as you mentioned (at least not yet).

I'll try to think of ways to streamline the `config-pin` process. In the meantime, I will use the workaround script you mentioned in PRUCookbook/docs/common/config-pin.sh.

**Comment by MarkAYoder** [comment]
@daschachter do a git pull and you should see my changes.

**Comment by daschachter** [comment]
Thank you @MarkAYoder, the updated `config-pin` is working on my end. Unfortunately, I am still running into issues with `gpio.pru0.c` -- I cannot get an LED connected to P2_05 to blink. I have tried accessing this GPIO through the terminal (sysfs) and I'm able to manually toggle the LED. I have also tried changing `gpio.pru0.c` to use pin P2_02 (GPIO1[27]), which, like P2_05, is not connected to R30. Strangely, this works (LED blinks when connected to P2_02). I am still not sure if this is a problem on my end, but I'll continue looking into this.

**Comment by MarkAYoder** [comment]
@daschachter this is odd.  When hooked to P2_05 you can blink the LED, but not via the pru.  And you can toggle an LED attached to P2_02 using the pru.  But you can't toggle an LED attached to P2_05 via the pru.  Seems like you've covered all the bases.

Are you sure when toggling P2_05 with the pru is it configured at 'out'?  (It should be if you can toggle it via /sys/.)

Maybe the pin is burned out.

**Comment by daschachter** [comment]
@MarkAYoder I've just confirmed that P2_05 is configured as 'out' -- I agree, this is very strange. The pin being burnt out is definitely a possibility. I'm not sure if you have a PocketBeagle on hand, but I'll try to reach out to someone with a PocketBeagle and see if they can confirm this behavior.

**Comment by MarkAYoder** [comment]
@daschachter were you ever able to get this to work?

**Comment by daschachter** [comment]
@MarkAYoder Unfortunately, I have not been able to get P2_05 working with the PRU. I suspect something has been burnt out on my board, like you mentioned previously. However, I'm currently working on a fix for `config-pin` (in the original source file) that should eliminate the issue with in/out modes. I'm hoping to have this fix done by the end of the week.

**Comment by daschachter** [comment]
The fix for `config-pin` is currently under review here: https://github.com/beagleboard/bb.org-overlays/pull/187 .

**Comment by majodu** [comment]
Also having trouble getting this example working. Not really sure how to debug it but there is one small difference I noticed
`/var/lib/cloud9/common/Makefile:28: MODEL=TI_AM335x_BeagleBone_Black,TARGET=gpio.pru0,COMMON=/var/lib/cloud9/common
/var/lib/cloud9/common/Makefile:147: GEN_DIR=/tmp/cloud9-examples,CHIP=am335x,PROC=pru,PRUN=0,PRU_DIR=/sys/class/remoteproc/remoteproc1,EXE=.out
-    Stopping PRU 0
/bin/sh: 1: echo: echo: I/O error
Cannot stop 0
-       copying firmware file /tmp/cloud9-examples/gpio.pru0.out to /lib/firmware/am335x-pru0-fw
write_init_pins.sh
-    Starting PRU 0
MODEL   = TI_AM335x_BeagleBone_Black
PROC    = pru
PRUN    = 0
PRU_DIR = /sys/class/remoteproc/remoteproc1`
under write_init_pins.sh there is no 
`writing "out" to "/sys/class/gpio/gpio30/direction"` line
