### ISSUE TITLE
resource_table_empty.h no more in pru-software-support-package

### ISSUE THREAD

**Issue by diplodocuslongus** [MarkAYoder/PRUCookbook#21]
Hello Mark,

Your work is of a great help but when trying to run through the examples, I couldn't find the header resource_table_empty.h in the latest tpru-software-support-package.
I am running a BB AI with bullseye, IOT image found here: https://forum.beagleboard.org/t/debian-11-x-bullseye-monthly-snapshots/31280/8 
Cloud9 is no more present in this release and it seems to break a lot of things, but as mentioned, above all, the header in question seems to be gone from TI's own package.
https://git.ti.com/cgit/pru-software-support-package/pru-software-support-package/

So I'm now trying to make my way through the examples provided in the latest pru-software-support-package but it lacks a blink LED sample!

Will you be updating your cookbook to get rid of the cloud9 dependencies?

**Comment by MarkAYoder** [comment]
Hi:
  There's a copy of the resource table in the **common** directory. (https://github.com/MarkAYoder/PRUCookbook/blob/master/docs/common/resource_table_empty.h)

I'll look in to converting from cloud9 to VS Code once VS Code is more stable.

I'm glad the cookbook is helpful.  It was fun to write.

--Mark
