### ISSUE TITLE
Errors in Makefile of  "Blinking a LED" example

### ISSUE THREAD

**Issue by majesty-dump** [MarkAYoder/PRUCookbook#4]
I got next errors while making Blinking a LED example:
root@beaglebone:/home/debian/PRUCookbook-master/docs/02start/code# make
Makefile:1: *** missing separator.  Stop.

After the first error i had copied makefile from "../../03details/code/Makefile" manually and tried to use "make" command again:

root@beaglebone:/home/debian/PRUCookbook-master/docs/02start/code# make
-    Stopping PRU 0
stop
CC      hello.c
"resource_table_empty.h", line 1: warning #1-D: last line of file ends without a newline
"resource_table_empty.h", line 1: error #171: expected a declaration
"hello.c", line 12: warning #12-D: parsing restarts here after previous syntax error
"hello.c", line 28: error #20: identifier "GPIO1_CLEAR" is undefined
2 errors detected in the compilation of "hello.c".

>> Compilation failure
Makefile:56: recipe for target '/tmp/pru0-gen/hello.obj' failed
make: *** [/tmp/pru0-gen/hello.obj] Error 1
  
 Is it only new  BeagleBone Black Kernel's  problems? 

version.sh :
git:/opt/scripts/:[73593ebe3b7d3cc381eeb502d45ccb33a6ec5e78]
eeprom:[A335BNLT00C02814BBBK2738]
model:[TI_AM335x_BeagleBone_Black]
dogtag:[BeagleBoard.org Debian Image 2018-08-30]
bootloader:[microSD-(push-button)]:[/dev/mmcblk0]:[U-Boot 2018.03-00002-gac9cce7                                                                                                                c6a]:[location: dd MBR]
kernel:[4.14.67-ti-r73]
nodejs:[v6.14.4]
uboot_overlay_options:[enable_uboot_overlays=1]
uboot_overlay_options:[uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC-4-14-TI-                                                                                                                00A0.dtbo]
uboot_overlay_options:[enable_uboot_cape_universal=1]
pkg check: to individually upgrade run: [sudo apt install --only-upgrade <pkg>]
pkg:[bb-cape-overlays]:[4.4.20180803.0-0rcnee0~stretch+20180804]
pkg:[bb-wl18xx-firmware]:[1.20180517-0rcnee0~stretch+20180517]
pkg:[kmod]:[23-2rcnee1~stretch+20171005]
pkg:[librobotcontrol]:[1.0.2-git20180829.0-0rcnee0~stretch+20180830]
pkg:[firmware-ti-connectivity]:[20170823-1rcnee1~stretch+20180328]
groups:[debian : debian adm kmem dialout cdrom floppy audio dip video plugdev us                                                                                                                ers systemd-journal i2c bluetooth netdev cloud9ide gpio pwm eqep admin spi tisdk                                                                                                                 weston-launch xenomai]
cmdline:[console=ttyO0,115200n8 bone_capemgr.uboot_capemgr_enabled=1 root=/dev/m                                                                                                                mcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet]
dmesg | grep pinctrl-single
[    1.109119] pinctrl-single 44e10800.pinmux: 142 pins at pa f9e10800 size 568
dmesg | grep gpio-of-helper
[    1.121264] gpio-of-helper ocp:cape-universal: ready
END

UPDATE:

In the end, I copied the **resource_table_empty.h** and **Makefile** files from the **03details** and **05blocks** folders , which paths  were codded in the simillar files  but  in the 02start folder. After all of that, the compilation was completed, but now I get the following warning every time i try to run Makefile:
`make: Warning: File 'Makefile' has modification time 2162757 s in the future`

**Comment by MarkAYoder** [comment]
I'll check into this next week.  I'd like to know what's happening.

Thanks for pointing it out.

--Mark

**Comment by MarkAYoder** [comment]
Hmmm....  It's working for me.

The last warning 

> make: Warning: File 'Makefile' has modification time 2162757 s in the future

is probably your clock on the Bone isn't set.  What does the 'date' command say?

```
bone$ date 
Wed Oct  3 15:21:53 EDT 2018
```

--Mark

**Comment by MarkAYoder** [comment]
p.s.  Did your source the setup.sh file first?

```
bone$ source setup.sh
#!/bin/bash
export PRUN=0
export TARGET=hello
echo PRUN=$PRUN
echo TARGET=$TARGET
bone$ make
-    Stopping PRU 0
stop
CC	hello.c
LD	/tmp/pru0-gen/hello.obj
-	copying firmware file /tmp/pru0-gen/hello.out to /lib/firmware/am335x-pru0-fw
-    Starting PRU 0
start
```

**Comment by majesty-dump** [comment]
> p.s. Did your source the setup.sh file first?
> 
> ```
> bone$ source setup.sh
> #!/bin/bash
> export PRUN=0
> export TARGET=hello
> echo PRUN=$PRUN
> echo TARGET=$TARGET
> bone$ make
> -    Stopping PRU 0
> stop
> CC	hello.c
> LD	/tmp/pru0-gen/hello.obj
> -	copying firmware file /tmp/pru0-gen/hello.out to /lib/firmware/am335x-pru0-fw
> -    Starting PRU 0
> start
> ```

Yes, i did it.

**Comment by MarkAYoder** [comment]
I'm pushing out a new version where this should work.  Check it out and reopen if it doesn't.

--Mark
