### ISSUE TITLE
python rendering issue

### ISSUE THREAD

**Issue by ceeaspb** [MarkAYoder/PRUCookbook#5]
In the neo-rainbow.py example it looks like asterisks are getting translated to <strong> resulting in invalid python code.

https://markayoder.github.io/PRUCookbook/05blocks/blocks.html#blocks_neo-rainbow

eg.
https://github.com/MarkAYoder/PRUCookbook/blob/master/docs/05blocks/blocks.html#L4678

**Comment by MarkAYoder** [comment]
Yup, it looks like the *'s are being used to BOLD.  I need to see how to fix it.

Thanks for pointing it out.
