### ISSUE TITLE
Can bbblue do it uart example?

### ISSUE THREAD

**Issue by wangyuanzhengbighead** [MarkAYoder/PRUCookbook#8]
my device is beaglebone blue. I refer to the 
when i When I execute this script :uart_setup.sh
export PRUN=0
export TARGET=uart1
echo PRUN=$PRUN
echo TARGET=$TARGET

Configure tx
config-pin P9_24 pru_uart

Configure rx
config-pin P9_26 pru_uart

then it will report error:
x$ config-pin P9.24 pru_uart
dash: echo: I/O error
Cannot write pinmux file: /sys/devices/platform/ocp/ocp:P9_24_pinmux/state
debian@beaglebone:/sys/devices/platform/ocp/ocp:P9_24_pinmux

Doesn't it need to be configured of the BBBLUE?
and how to start uart to send/receive data in bbblue？

**Comment by MarkAYoder** [comment]
Have you tried running the PRU without config-pin?  I think those pins are preconfigured to be UARTs.


--Mark
